依存関係をアップデートする
CPCTF2022/ssh-separator pull request #3
Opened 2022-02-24 15:29 UTC by Ras96

https://github.com/CPCTF2022/ansible/issues/9

- :up: Update to go1.17
- :up: Update dependencies
- :up: go generate

2022-02-25 03:37 UTC, hijiki51 requested changes
ちなみにこれテストとおってる？

2022-02-25 03:37 UTC, hijiki51 commented on .github/workflows/release.yml
> -            ghcr.io/mazrean/${{ env.USER_IMAGE_NAME }}:latest
IMAGEのpush先こっちでお願いします

```
asia-northeast1-docker.pkg.dev/cpctf-338715/problem/${{env.REPO_NAME}}:${{env.TAG}}
{{{

2022-02-25 03:37 UTC, hijiki51 commented on .github/workflows/release.yml
> -            ghcr.io/mazrean/${{ env.USER_IMAGE_NAME }}:latest
https://github.com/CPCTF2022/docker-problem-template

2022-02-25 03:37 UTC, hijiki51 commented on dev/docker-compose.yaml
> -      IMAGE_NAME: ghcr.io/mazrean/ssh-separator-ubuntu:latest
ここも変更

2022-02-25 03:37 UTC, hijiki51 commented on docker-compose.yaml
> -    image: ghcr.io/mazrean/ssh-separator:latest
ここも

2022-02-25 03:49 UTC, Ras96 commented
> ちなみにこれテストとおってる？

通ってた
publicだしactions導入してもいいかも

2022-02-25 03:56 UTC, hijiki51 commented
そういえばそうだね

2022-02-25 03:56 UTC, Ras96 commented on dev/docker-compose.yaml
> -      IMAGE_NAME: ghcr.io/mazrean/ssh-separator-ubuntu:latest
ここは
```
      IMAGE_NAME: asia-northeast1-docker.pkg.dev/cpctf-338715/problem/ssh-separator:latest
```
であってる？ssh-separator-ubuntuとかじゃなくて

2022-02-25 03:57 UTC, hijiki51 commented
それもお願いしていい？

2022-02-25 03:57 UTC, Ras96 commented
ok

2022-02-25 03:58 UTC, hijiki51 commented on dev/docker-compose.yaml
> -      IMAGE_NAME: ghcr.io/mazrean/ssh-separator-ubuntu:latest
あ～それ問題用のテンプレートレポジトリからコピペしてきたやつだ

2022-02-25 03:59 UTC, hijiki51 commented on dev/docker-compose.yaml
> -      IMAGE_NAME: ghcr.io/mazrean/ssh-separator-ubuntu:latest
systemってバケット作るので
`asia-northeast1-docker.pkg.dev/cpctf-338715/system/{repo}:{tag}`

ubuntuだし、ARM使う予定はないのでそれでいいです
で

2022-02-25 04:07 UTC, hijiki51 requested changes

2022-02-25 04:07 UTC, hijiki51 commented on .github/workflows/release.yml
>            registry: ghcr.io
ログイン先は`ghcr.io`じゃなくてGAR(Google Artifact Registory)です（docker-login-action）の公式見ればわかるはず

2022-02-25 04:07 UTC, hijiki51 commented on dev/docker-compose.yaml
> -      IMAGE_NAME: ghcr.io/mazrean/ssh-separator-ubuntu:latest
｛｝の中は変数の意味なのでいい感じに置換するなり指定してください

2022-02-25 04:07 UTC, hijiki51 commented on .github/workflows/release.yml
> -            ghcr.io/mazrean/${{ env.USER_IMAGE_NAME }}:latest
ここ変わってない

2022-02-27 14:45 UTC, hijiki51 requested changes

2022-02-27 14:45 UTC, hijiki51 commented on .github/workflows/release.yml
> +          password: ${{ steps.auth.outputs.access_token }}
この書き方は、
`(以前に実行されたステップのうち).(id=authのものの).(出力結果のうち).(access_token)`っていう書き方なので前のstepに`id: auth`がないと意味ないです


で、今回はpasswordは`__json_key`でぶち込む予定です


https://github.com/CPCTF2022/docker-problem-template/blob/main/.github/workflows/build.yaml

↑参考にしてください

2022-02-27 14:45 UTC, hijiki51 commented on .github/workflows/release.yml
> +            asia-northeast1-docker.pkg.dev/cpctf-338715/problem/${{env.REPO_NAME}}:${{env.TAG}}
ここproblemじゃなくてsystemでよろしく（こっちのほう指示するの忘れてた）

2022-02-27 14:45 UTC, hijiki51 commented on .github/workflows/release.yml
> +          password: ${{ steps.auth.outputs.access_token }}
同上

2022-02-27 14:45 UTC, hijiki51 commented on .github/workflows/release.yml
> +            asia-northeast1-docker.pkg.dev/cpctf-338715/problem/${{env.REPO_NAME}}:latest
ここも

2022-02-27 14:45 UTC, hijiki51 commented on .github/workflows/release.yml
> +            asia-northeast1-docker.pkg.dev/cpctf-338715/problem/${{env.REPO_NAME}}:${{env.TAG}}
これ環境変数にREPO_NAMEとTAGを追加しないといけません。

https://github.com/CPCTF2022/docker-problem-template/blob/main/.github/workflows/build.yaml

↑だとGITHUB_REFからとってきてる

2022-02-27 14:45 UTC, hijiki51 commented on docker-compose.yaml
> +    image: asia-northeast1-docker.pkg.dev/cpctf-338715/system/{repo}:{tag}
同様にここの`{}`も変数なので置き換えてください

2022-02-27 16:13 UTC, Ras96 commented on .github/workflows/release.yml
> +          password: ${{ steps.auth.outputs.access_token }}
docker-problem-templateは`_json_key`って書いてあるけどどっちが正しいですか
後確認だけど
```
```

2022-02-27 16:23 UTC, hijiki51 commented on .github/workflows/release.yml
> +          password: ${{ steps.auth.outputs.access_token }}
`_json_key`が正しいです

https://github.com/docker/login-action#service-account-based-authentication

2022-02-27 16:57 UTC, hijiki51 commented on docker-compose.yaml
> +    image: asia-northeast1-docker.pkg.dev/cpctf-338715/system/{repo}:{tag}
これ変わってない

2022-02-28 17:42 UTC, merged